Repository legendarysandbird/3mc-game, pull requests merged in 2025-04, with the labels that each got.

#8 Add basic 2D character controller, temp level, and temp animations
  assets/level/tilesheet_complete.png
  assets/level/tilesheet_complete.png.import
  assets/player_temp/playerBlue_stand.png
  assets/player_temp/playerBlue_stand.png.import
  assets/player_temp/playerBlue_walk1.png
  assets/player_temp/playerBlue_walk1.png.import
  assets/player_temp/playerBlue_walk2.png
  assets/player_temp/playerBlue_walk2.png.import
  assets/player_temp/playerBlue_walk3.png
  assets/player_temp/playerBlue_walk3.png.import
  icon.svg
  project.godot
  scenes/player.tscn
  scenes/temp_level.tscn
  scripts/player.gd
  scripts/player_animation.gd
Labels: enhancement

#9 idle-LR-animations
  assets/player_temp/idle/01-idle-1024.png
  assets/player_temp/idle/01-idle-1024.png.import
  assets/player_temp/idle/02-idle-1024.png
  assets/player_temp/idle/02-idle-1024.png.import
  assets/player_temp/idle/03-idle-1024.png
  assets/player_temp/idle/03-idle-1024.png.import
  assets/player_temp/idle/04-idle-1024.png
  assets/player_temp/idle/04-idle-1024.png.import
  assets/player_temp/idle/05-idle-1024.png
  assets/player_temp/idle/05-idle-1024.png.import
  assets/player_temp/idle/06-idle-1024.png
  assets/player_temp/idle/06-idle-1024.png.import
  assets/player_temp/walk/01-H34R1L355-character-LR-1024px.png
  assets/player_temp/walk/01-H34R1L355-character-LR-1024px.png.import
  assets/player_temp/walk/02-H34R1L355-character-LR-1024px.png
  assets/player_temp/walk/02-H34R1L355-character-LR-1024px.png.import
  assets/player_temp/walk/03-H34R1L355-character-LR-1024px.png
  assets/player_temp/walk/03-H34R1L355-character-LR-1024px.png.import
  assets/player_temp/walk/04-H34R1L355-character-LR-1024px.png
  assets/player_temp/walk/04-H34R1L355-character-LR-1024px.png.import
  assets/player_temp/walk/05-H34R1L355-character-LR-1024px.png
  assets/player_temp/walk/05-H34R1L355-character-LR-1024px.png.import
  assets/player_temp/walk/06-H34R1L355-character-LR-1024px.png
  assets/player_temp/walk/06-H34R1L355-character-LR-1024px.png.import
  scenes/player.tscn
Labels: art

#12 Update player collision node for new assets
  scenes/player.tscn
  scripts/player.gd
Labels: enhancement, art

#11 Update player_animation.gd > animate() logic
  assets/player_temp/playerBlue_stand.png
  assets/player_temp/playerBlue_stand.png.import
  assets/player_temp/playerBlue_walk1.png
  assets/player_temp/playerBlue_walk1.png.import
  assets/player_temp/playerBlue_walk2.png
  assets/player_temp/playerBlue_walk2.png.import
  assets/player_temp/playerBlue_walk3.png
  assets/player_temp/playerBlue_walk3.png.import
  scenes/player.tscn
  scripts/player_animation.gd
Labels: bug, art

#13 Add basic player slope movement
  scenes/player.tscn
  scenes/temp_level.tscn
  scripts/player.gd
Labels: enhancement

#16 Create Enemy Movement Script
  project.godot
  scenes/enemy.tscn
  scenes/player.tscn
  scenes/temp_level.tscn
  scripts/auto-loads/groups.gd
  scripts/enemy.gd
  scripts/player.gd
Labels: enhancement

#17 enemy-01 animations
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-01.png
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-01.png.import
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-02.png
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-02.png.import
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-03.png
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-03.png.import
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-04.png
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-04.png.import
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-05.png
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-05.png.import
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-06.png
  assets/enemies_temp/enemy-01_singularity/aggro/Singularity-aggro-06.png.import
  assets/enemies_temp/enemy-01_singularity/enemy-01.tscn
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-01.png
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-01.png.import
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-02.png
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-02.png.import
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-03.png
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-03.png.import
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-04.png
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-04.png.import
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-05.png
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-05.png.import
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-06.png
  assets/enemies_temp/enemy-01_singularity/idle/Singularity-idle-06.png.import
Labels: art
